In [60]:
#Solve Ax=b using Gauss Elimination and LU Decomposition

import numpy as np

A = np.array([[1., -1., 2.], [1., 2., 3.], [3., -4., -5.]])
b = np.array([3., 5., -13.])

print("A =\n{}".format(A))
print("b = {}".format(b))

A =
[[ 1. -1.  2.]
 [ 1.  2.  3.]
 [ 3. -4. -5.]]
b = [  3.   5. -13.]


In [62]:
#Gauss Elimination Method

factor = 1
for i in range(b.size):
    for j in range(i+1, b.size):
        factor = A[j, i] / A[i, i]
        A[j, i:] = A[j, i:] - factor * A[i, i:]
        b[j] = b[j] - factor * b[i]
        print("------------------------")
        print("A = \n {}".format(A))
        print("b = {}".format(b))
        print("------------------------")

x = np.zeros(b.size)

for i in range(b.size - 1, -1, -1):
    x[i] = (b[i] - A[i, i+1:] @ x[i+1:]) / A[i, i]

print("From Gauss Elimination Method, the value of x is {}".format(x))

------------------------
A = 
 [[  1.          -1.           2.        ]
 [  0.           3.           1.        ]
 [  0.           0.         -10.66666667]]
b = [  3.           2.         -21.33333333]
------------------------
------------------------
A = 
 [[  1.          -1.           2.        ]
 [  0.           3.           1.        ]
 [  0.           0.         -10.66666667]]
b = [  3.           2.         -21.33333333]
------------------------
------------------------
A = 
 [[  1.          -1.           2.        ]
 [  0.           3.           1.        ]
 [  0.           0.         -10.66666667]]
b = [  3.           2.         -21.33333333]
------------------------
From Gauss Elimination Method, the value of x is [-1.  0.  2.]
