In [100]:
#Solve Ax=b using Gauss Elimination and LU Decomposition

import numpy as np

P = np.array([[1., -1., 2.], [1., 2., 3.], [3., -4., -5.]])
Q = np.array([3., 5., -13.])

#Because there are two different methods, original matrices are P and Q which will be copied as A and b, for Ax=b
print("A =\n{}".format(P))
print("b = {}".format(Q))

A =
[[ 1. -1.  2.]
 [ 1.  2.  3.]
 [ 3. -4. -5.]]
b = [  3.   5. -13.]


In [101]:
#Gauss Elimination Method

A = P.copy()
b = Q.copy()

for i in range(b.size):
    for j in range(i+1, b.size):
        factor = A[j, i] / A[i, i]
        A[j, i:] = A[j, i:] - factor * A[i, i:]
        b[j] = b[j] - factor * b[i]
        print("------------------------")
        print("A = \n {}".format(A))
        print("b = {}".format(b))
        print("------------------------")

x = np.zeros(b.size)

#backward 
for i in range(b.size - 1, -1, -1):
    x[i] = (b[i] - A[i, i+1:] @ x[i+1:]) / A[i, i]

print("From Gauss Elimination Method, the value of x is {}".format(x))

------------------------
A = 
 [[ 1. -1.  2.]
 [ 0.  3.  1.]
 [ 3. -4. -5.]]
b = [  3.   2. -13.]
------------------------
------------------------
A = 
 [[  1.  -1.   2.]
 [  0.   3.   1.]
 [  0.  -1. -11.]]
b = [  3.   2. -22.]
------------------------
------------------------
A = 
 [[  1.          -1.           2.        ]
 [  0.           3.           1.        ]
 [  0.           0.         -10.66666667]]
b = [  3.           2.         -21.33333333]
------------------------
From Gauss Elimination Method, the value of x is [-1.  0.  2.]


In [103]:
#LU decomposition method

L = np.eye(b.size)
U = P.copy()
b = Q.copy()

#A = L @ U
for i in range(b.size):
    for j in range(i+1, b.size):
        factor = U[j, i] / U[i, i]
        L[j, i] = factor
        U[j, i:] = U[j, i:] - factor * U[i, i:]

print("L =\n {}".format(L))
print("U =\n {}".format(U))

#solve for y: L @ y = b
y = np.zeros(b.size)

#forward substitution
for i in range(b.size):
    y[i] = b[i] - L[i, :i] @ y[:i]

#solve for x: U @ x = y
x = np.zeros(b.size)

#backward subsitution
for i in range(b.size - 1, -1, -1):
    x[i] = (y[i] - U[i, i+1:] @ x[i+1:]) / U[i, i]

print("From LU decompositon method, the value of x is {}".format(np.round(x, 10)))

L =
 [[ 1.          0.          0.        ]
 [ 1.          1.          0.        ]
 [ 3.         -0.33333333  1.        ]]
U =
 [[  1.          -1.           2.        ]
 [  0.           3.           1.        ]
 [  0.           0.         -10.66666667]]
From LU decompositon method, the value of x is [-1. -0.  2.]
