In [27]:
#vector and matrix

import numpy as np

#define two vectors
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

#define two matrices
m1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#printing all the vectors and matrices
print("v1: {}".format(v1))
print("v2: {}".format(v2))
print("m1:\n {}".format(m1))
print("m2:\n {}".format(m2))

v1: [1 2 3]
v2: [4 5 6]
m1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
m2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
#addition and subtraction

print("Addition:")
print(v1 + v2)
print(m1 + m2)

print("Subtraction:")
print(v1 - v2)
print(m1 - m2)

Addition:
[5 7 9]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Subtraction:
[-3 -3 -3]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [19]:
#dot product

dot = 0
for i in range(v1.size):
    dot = dot + v1[i] * v2[i]

print("Dot product of two vectors: {}".format(dot))

#dot product using @
dot = v1 @ v2
print("Dot product using @: {}".format(dot))

Dot product of two vectors: 32
Dot product using @: 32


In [14]:
#matrix multiplication
mul = np.zeros((m1.shape[0], m2.shape[1]))
if(m1.shape[1] == m2.shape[0]):
    for i in range( m1.shape[0] ):
        for l in range( m2.shape[1] ):
            for j in range ( m1.shape[1] ):
                mul[i , l] = mul[i, l] + m1[i, j] * m2[j, l]
else:
    print("matrix multiplication is not possible")

print("Matrix multiplication of the two matrices:\n {}".format(mul))

#matrix multiplication using @
mul = m1 @ m2
print("Matrix multiplication using @:\n {}".format(mul))

Matrix multiplication of the two matrices:
 [[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]
Matrix multiplication using @:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [4]:
#Transpose of a matrix

transpose = np.zeros((m1.shape[0], m1.shape[1]))
for i in range(m1.shape[0]):
    for j in range(m1.shape[1]):
        transpose[i, j] = m1[j, i]

print("Transpose of the matrix:\n {}".format(transpose))

Transpose of the matrix:
 [[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [29]:
#Norm of a vector

#L2 norm (Euclidean Norm)

sum = 0
for i in range(v1.size):
    sum = sum + v1[i] * v1[i]

print("L2 (Euclidean) Norm: {}".format(np.sqrt(sum)))
print("L2 using numpy: {}".format(np.linalg.norm(v1)))

#L1 norm (Manhatten Norm)

sum = 0
for i in range(v1.size):
    sum = sum + abs(v1[i])

print("L1 (Manhattan Norm: {}".format(sum))
print("L1 using numpy: {}".format(np.linalg.norm(v1, 1)))

#L-infinity norm (Maximum Norm)

maximum = 0
if(v1.size == 1):
    maximum = v1[0]
else:
    for i in range(v1.size):
        if(i != (v1.size - 1)):
            if(abs(v1[i]) > abs(v1[i+1])):
                maximum = abs(v1[i])
            else:
                maximum = abs(v1[i+1])

print("L-infinity (Maximum) Norm: {}".format(maximum))
print("L-infinity using numpy: {}".format(np.linalg.norm(v1, np.inf)))

L2 (Euclidean) Norm: 3.7416573867739413
L2 using numpy: 3.7416573867739413
L1 (Manhattan Norm: 6
L1 using numpy: 6.0
L-infinity (Maximum) Norm: 3
L-infinity using numpy: 3.0
