In [9]:
#vector and matrix

import numpy as np

#define two vectors
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

#define two matrices
m1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [14]:
#addition and subtraction

print("Addition:")
print(v1 + v2)
print(m1 + m2)

print("Subtraction:")
print(v1 - v2)
print(m1 - m2)

Addition:
[5 7 9]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Subtraction:
[-3 -3 -3]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [18]:
#dot product

dot = 0
for i in range(v1.size):
    dot = dot + v1[i] * v2[i]

print("Dot product of two vectors: {}".format(dot))

#dot product using @
dot = v1 @ v2
print("Dot product using @: {}".format(dot))

Dot product of two vectors: 32
Dot product using @: 32


In [22]:
#matrix multiplication

if(m1.shape[1] == m1.shape[0]):
    for i in range(m1.shape[0]):
        for j in range(m1.shape[1]):
            
else:
    print("matrix multiplication is not possible")

matrix multiplication is possible
